### PR TITLE
Tutorial fixes after a UX study:

### PR DESCRIPTION
**Pull request by dabreegster**
- Fix a typo
- Draw a star on the car that the player is supposed to follow
- Move the message panel to the left when pointing to the minimap and
  layers
- Add button icons to the message box to really emphasize what we're
  pointing to

# Before/after's

A few people have reported issues figuring out which car to follow, especially when their window size messes up.
Screenshot from 2021-04-16 14-05-25
So why don't we just draw a star on that car for the entire tutorial step?
Screenshot from 2021-04-16 14-06-38
Happy to adjust size/color/icon.

We kind of fail at pointing to the "layers" button, because the message box overlaps the minimap:
Screenshot from 2021-04-16 14-07-15
So let's move that message box over, and also add the layer icon to the message box.
Screenshot from 2021-04-16 14-07-55

Every time we point to a button, we can include that icon to really emphasize it:
Screenshot from 2021-04-16 14-08-47

# Not sure about these problems

Yuwen raised the idea of changing the follow car challenge to not require clicking the parked car and using the "wash me" button. We could just ask people to click the car to follow it, then wait for it to park, then that's it. But I feel like it could be useful to understand that following a person will refocus the info panel onto a building when they go inside. And the car is parked right out front, with nothing else around.

We also saw issues during the "Exploring map layers" task for finding low parking. One of the messages tells you how to move the map by dragging on the minimap. The next message tells you about the layers button. Really these are kind of different concepts to introduce, and we really want to emphasize that the list of layers should be explored. I could split things out, but I feel like we ought to have some task for testing control by the minimap. Any ideas?

### CODE REVIEW

**Review by michaelkirk — APPROVED** [review]
LGTM

**Comment by michaelkirk** [comment]
> We also saw issues during the "Exploring map layers" task for finding low parking. One of the messages tells you how to move the map by dragging on the minimap. The next message tells you about the layers button. Really these are kind of different concepts to introduce, and we really want to emphasize that the list of layers should be explored. I could split things out, but I feel like we ought to have some task for testing control by the minimap. Any ideas?

The point of the minimap is that you can navigate relatively long distances quickly, while staying zoomed in. So, we need to observe something in detail (zoomed in), over a vast area.

Could we do some kind of where's Wally? 

And maybe Wally only likes to hang out at certain elevations.

**Comment by michaelkirk** [comment]
> Yuwen raised the idea of changing the follow car challenge to not require clicking the parked car and using the "wash me" button. We could just ask people to click the car to follow it, then wait for it to park, then that's it. But I feel like it could be useful to understand that following a person will refocus the info panel onto a building when they go inside. And the car is parked right out front, with nothing else around.

I think this might also be the first example of clicking a button within an info panel.

I don't really have strong feelings about getting rid of it one way or the other.

**Comment by dabreegster** [comment]
Whoops, I guess I could've merged this _before_ cutting the release. Merging now, will check designs with Yuwen later and iterate.

> And maybe Wally only likes to hang out at certain elevations.

This is an awesome idea! Filed #611 to track

**Pull request merged**
