### PR TITLE
Update planter rendering

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Heads-up @dabreegster I noticed the svg was a lot terser in your version. I edited it in InkScape. Do you want me to make the svg file more compact? If so any ideas how would be appreciated.

**Comment by dabreegster** [comment]
Ooh, thank you for making the color/style way more planter-like! This looks fantastic.

I know a few tricks for simplifying SVG:

1) I made a spare [Figma](figma.com) document where I upload SVGs. If you then select the object in Figma, right click, and copy it as SVG, it's simplified. Figma even collapses some of the fancier SVG features into simpler path operations.
2) [resvg](https://github.com/RazrFalcon/resvg) has a CLI tool. You can `cargo install usvg`, then `usvg input.svg simplified_output.svg`
3) Inkscape "save as" has some options for "plain SVG"

**Comment by Robinlovelace** [comment]
> Inkscape "save as" has some options for "plain SVG"

Tried that - that's the simplified output. There may be more options, will check as that's the simplest solution (no need for extra software/web services).

**Comment by michaelkirk** [comment]
You can also edit them "by hand" in a text editor and remove the unnecessary elements, like the `<?xml` declaration, and the `metadata` tag.

**Comment by Robinlovelace** [comment]
Seems a common issue: https://inkscape.org/forums/questions/too-much-junk-on-svg-format/ I'm going for the usvg solution next, loving Rust CLI tools.

**Comment by dabreegster** [comment]
`usvg` is also the SVG rendering library that powers A/B Street. ;)

If you have any issues getting it to work, I can also run the tool on my end. Guess it's time to take a breather from intersection consolidation and push through this bike buffer work!

**Comment by Robinlovelace** [comment]
Reproducible code used to update the .svg file in the commit above:

```
cargo install usvg
cd data/system/assets/edit/buffer/
usvg planters.svg planters.svg
git commit -am 'Update planter - simplify'
git push rl
history 15 | cut -c 8-
```

**Comment by dabreegster** [comment]
Thanks for the help with color! Merging. I'll revive #704 and aim to get something committed today.

**Pull request merged**
