### PR TITLE
Add regular file dialogs for saving/loading LTN files

### PR DESCRIPTION
**Pull request by dabreegster**
Previously, the LTN tool had its own custom file management paradigm. Files can be saved under a name, and loaded from a (flat / unorganized) list of names. Internally, they're stored as gzipped JSON files natively, or encoded in local storage on the web. The UI looked like this:

https://user-images.githubusercontent.com/1664407/234373787-4b26ca49-11bc-494d-a071-9d4469d8ce19.mp4

I got feedback from a user of the native (not web) app in #1082. They want the traditional file management workflow; they're used to internally emailing files or using their own cloud storage. The way the LTN tool hides the files is confusing to them. So in this PR, I added a parallel save/load button that uses regular file dialogs:

https://user-images.githubusercontent.com/1664407/234374247-9a935468-f4fb-43c7-8390-c68897fe3930.mp4

I think this will help their use case in the short term, and hopefully not be too confusing to everyone else. The feature works fine on native, but on web, saving the files currently doesn't work. (It can, I just haven't figured out exactly how yet -- see later comments in this PR).

Now for the UX warts. We have two save and load tools, "quick" (the classic list-based thing) and "file" (the new thing):
Screenshot from 2023-04-25 19-51-17
It's for sure confusing to have both, and the names are not great. Any ideas? Maybe we should use the classic "quick" one by default, but add a very prominent "let me save/load files in a normal way using my OS" button, on this screen:
Screenshot from 2023-04-25 19-52-50

Note when the left sidebar is collapsed, there's only one save/load icon, and it does the old style by default:
Screenshot from 2023-04-25 19-53-23

Finally, the old-style save dialog is normally the place to define a proposal name. Maybe we should use the filename now when using the new flow? Otherwise the proposal names that show up in the left sidebar get kind of out-of-sync.

### CODE REVIEW

**Review by dabreegster — COMMENTED** [review]
@andrewphilipsmith since you're starting to look at the LTN tool, I figured it'd make sense to keep you in the loop on changes. This is not a great first example PR; I promise usually there's less crazy code changes. Here it's just to introduce file saving dialogs that work on native/web and workaround some mess. If you have some time, I'd appreciate input on the UX questions I raised in the PR. Understanding the code is less important (because it's messy and most of what we'll be doing won't have to dig into such hairy platform-specific details)

**Comment by dabreegster** [comment]
Based on https://github.com/a-b-street/abstreet/issues/765#issuecomment-1522493746, I nested the native file dialogs underneath the existing controls.

https://user-images.githubusercontent.com/1664407/234541180-c24d6f35-9ef0-4dee-97a7-393c01cdaad0.mp4

I think this is now reasonably coherent, so I'll merge. There are still some confusing things left, but I'll record in #1082

**Comment by andrewphilipsmith** [comment]
@dabreegster I like the way you've combined the save-within-app and save-as-seperate-file options.

My only thought is about the default directory for the load/save file dialogue:
- The default to the "internal" data directory (eg data/player/ltn_proposals/gb/<location>/center/) might not be intuitive for all users.
- Maybe default to either their home directory or the most recently used directory?

Would you prefer this in #1082?

**Comment by dabreegster** [comment]
@andrewphilipsmith, thanks for reviewing!

> Maybe default to either their home directory or the most recently used directory?

This is related to #804, the fact that A/B Street expects "system" files (maps downloaded from S3) and "player" files (like LTN proposals) to be in certain directories with a structure that's based on the map name (gb/poundbury/center). Detangling that or making it configurable (necessary for #804, allowing proper packaging in various OSes) is kind of tough, but doable. But I guess here you're suggesting something simpler -- the default load dialog already lists files in that canonical directory, so if someone wants to use their OS file picker, then starting them somewhere else makes sense.

If we don't call `set_directory`, on Linux it's defaulting to the directory where the executable is -- also not useful. I'll look around for Rust crates that give the user's home directory on Windows/Mac/Linux. I like that as a better default.

We could move further conversation to #1082 or keep it here; either way

**Comment by dabreegster** [comment]
Changed to the user's home directory in 43b4f1605366e47bd58283b13b2f28499e0798de

**Pull request merged**
