### PR TITLE
Apply an initial camera zoom when passing the --cam param. For

### PR DESCRIPTION
**Pull request by dabreegster**
https://github.com/cyipt/actdev/issues/44

To try this out:
1) Go somewhere on OSM, like https://www.openstreetmap.org/#map=17/47.64118/-122.31143
2) Copy that parameter and run `cargo run -- --dev --cam=17/47.64118/-122.31143`

For me, OSM is:
Screenshot from 2021-02-04 20-52-59
And abst:
Screenshot from 2021-02-04 20-54-28

I circled the same spots on both. As you can see, this matches up _pretty_ well, but abst is always a bit too big. I can't figure out why. Of course the abst window height is a little more generous, without OSM's top header, but I'd expect things to at least line up horizontally.

@michaelkirk This might be good enough for the actdev integration (browse a normal slippy web map, then press a button to jump to the same point in abst), but I figured you might spot the likely silly problem with my math.

### CODE REVIEW

**Comment by michaelkirk** [comment]
Sorry, I forgot about this 😓 

I don't immediately know what's going on but I'll pull it down and see if I can deduce anything...

**Comment by michaelkirk** [comment]
First observation - if I disable window maximization, and resize the OSM window to whatever the initial window size is, things line up pretty good!

```diff
diff --git a/widgetry/src/backend_glow_native.rs b/widgetry/src/backend_glow_native.rs
index 6fc934479..dff9201cd 100644
--- a/widgetry/src/backend_glow_native.rs
+++ b/widgetry/src/backend_glow_native.rs
@@ -9,8 +9,8 @@ pub fn setup(
 ) -> (PrerenderInnards, winit::event_loop::EventLoop<()>) {
     let event_loop = winit::event_loop::EventLoop::new();
     let window = winit::window::WindowBuilder::new()
-        .with_title(window_title)
-        .with_maximized(true);
+        .with_title(window_title);
+        // .with_maximized(true);
```

https://user-images.githubusercontent.com/217057/107304308-a8a30900-6a35-11eb-94ec-788648079df8.mp4

Maybe implicating something in our resize logic - maybe there is some confusions with calculating the zoom WRT initial dimensions vs. the dimensions once everything has settled.

**Comment by michaelkirk** [comment]
To clarify my hypothesis - window resizing is an async thing, so maybe we are doing calculations with the initial size, when we really want them to be done with our *final* size.

**Comment by dabreegster** [comment]
> so maybe we are doing calculations with the initial size, when we really want them to be done with our final size

Bingo! I totally forgot about this, even though it's obvious every time there's a sequence of loading screens on Linux. Thanks for debugging!

I'll go ahead and merge this for now, and think about how to run it deferred a few events in. Since this is an issue that also affects loading screens, I'm somewhat considering deferring running any widgetry caller code until a few events have come through winit. Maybe process window events until something like a 0.001s timeout, then run the user code.

**Pull request merged**
