### PR TITLE
Quick prototype of Streetcomplete colors and an explicit curb

### PR DESCRIPTION
**Pull request by dabreegster**
This is a followup to @westnordost's suggestion in #704 to draw a more explicit curb between the road and sidewalk. I incorporated a few more ideas here too, pulling lots of colors from Streetcomplete (https://user-images.githubusercontent.com/7988080/103153247-827c1f00-478f-11eb-9d1f-4d12017533aa.png) and also its map style (https://raw.githubusercontent.com/ENT8R/streetcomplete-mapstyle/gh-pages/images/light.png). I'm **really** liking how things are looking and am considering a big color overhaul based around this. Any initial feedback? @Robinlovelace, @michaelkirk, @trangrei

Some of the changes:
- Using Streetcomplete colors for the map background, water, parks, unzoomed roads
- Drawing a bold line between the road and curb. (There are some bugs near intersections that I'll fix if we decide to push forward with this style.)
- Use Streetcomplete color for zoomed-in lanes
- Stop coloring intersections and parking lanes a different color. It usually doesn't match reality; just show paved surface, and add markings on top of that.

If we go forward with this, there's lots of code simplification I'll do, and rethinking the styling for bike/bus lanes, access-restricted roads, night mode, etc. Also need to make sure layers and agents look good on this scheme.

We could also just incorporate a few of the ideas -- the color changes and adding the curb could be independent steps.

Before:
Screenshot from 2021-07-23 13-04-15
After:
Screenshot from 2021-07-23 13-04-24

Before:
Screenshot from 2021-07-23 13-03-38
After:
Screenshot from 2021-07-23 13-03-19

Before:
Screenshot from 2021-07-23 13-05-46
After:
Screenshot from 2021-07-23 13-05-39

### CODE REVIEW

**Comment by westnordost** [comment]
Wow, cool, I feel honored you were inspired by [StreetComplete](https://github.com/streetcomplete/StreetComplete)! I'd like to give you feedback on this too:

# Background

**Note** that this map style ([link to a demo slippy map](https://streetcomplete.github.io/streetcomplete-mapstyle/)) with its subtle pastel tones was created with the purpose of serving as a **background map** that is used for orientation only with the goal to not divert so much visual attention from the real focal point of the app: The map pins.
streetcomplete

The purpose of the map is different for your app:
- For the minimap, you probably want a **good overview** for orientation, with a **focus on the street layout and arterial roads**
- For the main view, the **focus is on street layout**, so that should stand out while the rest is secondary

Now, of course I wouldn't have created that map style together with @ENT8R if I wouldn't also find the map colors visually pleasing. I just think that based on your requirements, you might want to make a few adjustments.

# Positive Feedback

- I think the dark border on the sidewalk that represents the curb looks very good!
- I like that the standard background is not light grey but this light beige. When all shades of gray are reserved for streets, they stand out better. Also it adds a little variation in color, which is nice
- I also like the more subtle green for green areas. As the green areas are really not anything important in your app, it is much better if they don't stand out that much
- I like that you removed the color difference from street and intersection because this is a technical detail that is not interesting for the user
- The sidewalk is now better distinguishable from the background, wich is good

# Suggestions for changes

### Main View
- since the street layout is the focus point of the app, I'd go with higher contrast here (darker asphalt surface).
- again, as the street layout is the focus point, in general it is OK to use more flashy colors as for the background map. The green cycle lanes are already flashy. Specifically, I would definitely make the parking lanes stand out from the roads in one way or another - maybe use blue as a background? In your current prototype, it is not good that they are not so well distinguishable from a normal car lane
- The reason why buildings on the streetcomplete-mapstyle are light gray blue is to better distinguish them from other elements. This is even more relevant for your use case: Your streets are road. You would not want anything else that is not a road be gray too so that this could be confounded with roads.
- The zebra strip spacing seems to be messed up. Should be either thicker equally spaced lines or thin lines like here  ([source](https://www.bikeauckland.org.nz/nelson-st-phase-2-gets-underway/))
- Even if there is no sidewalk and thus maybe no curb, I'd experiment with always drawing such a dark kurb line at the border of a street surface, just so that it visually "lifts off" from thebackground map a little
- The green turn arrows were better visible before. Maybe you should think of a color/hue that is not used on streets and reserve that color for such arrows (green is used, by cycleways). I guess these must be especially flashy because they should stand out from the road which already stands out - Orange maybe?
- Road names on the streets add to visual clutter. I.e. there is already a lot going on the streets itself, you'd not want to have elements that don't need to be **on** the street to take up space. Suggestion: Move the street name to beside the street (on the beige background). Then, they could also be larger, in the background

### Minimap

Roads should stick out more. You could try

- give motorways a distinctly different color than any other road
- use different colors for roads with different numbers of lanes, i.e. large arterials are f.e. redder than less important roads
- maybe don't even display buildings or make them even more subtle
- alternatively, you could try giving the roads a thin (gray) border so they stand out from the background more

**Comment by Robinlovelace** [comment]
Big and broad :+1: for the general direction of travel indicated by the images at the top of this PR. Not looked at detail, looks like plenty of detailed comments which sound sensible to me. I think these are definite improvements to the aesthetics and are good enough for now and safe enough to try: the overall feel of the new colours is more pro and subtle IMO, enabling grey roads which are easier on the eye. I agree with @westnordost's comments, especially that

> When all shades of gray are reserved for streets, they stand out better. Also it adds a little variation in color, which is nice

Also :+1: to this suggestion (I have the same strong preference for roads that do not allow through traffic for large motor vehicles which I think would work well as a shade of grey-green - linked to #660 ):

> Specifically, I would definitely make the parking lanes stand out from the roads in one way or another - maybe use blue as a background

and simplifying the minimap.

**Comment by michaelkirk** [comment]
I agree with everything @westnordost said. Thanks for taking the time to look!

> The green turn arrows were better visible before. 

Part of the issue I think is that these arrows animate: starting bright and fading as the signal is about to change - this isn't apparent in the screenshots, so they just look worse than they actually are in game play:



But even when they are fully opaque, I do think some contrast was lost, e.g. in this one:


Also unfortunate: because of the lightening of the background, the "yield" turns, which are dashed and outlined, now appear more prominent than the straight arrows, which I think is the opposite of what we want.

Maybe either: outline the straight arrows (and probably add a z-index to the straight arrows to avoid collision?) -or- lighten the outline around the dashed arrows.

**Comment by dabreegster** [comment]
Wow, thank you all for the detailed feedback! Loads of ideas surfacing. To not lose track, I'm iterating on some of them under the experiment flag of an existing alternative color scheme. In particular, the curb geometry is now improved, though there are still some bugs I know about.

Screenshot from 2021-07-25 13-55-33

Not to increase the scope of this color revamp even more, but one possibility it might open is to expose the road classification (highway, arterial, residential) in the zoomed-in view. This is something I've wanted to do since the very beginning, because it's easy to get disoriented when zoomed in. And unlike other renderers, just drawing arterial roads with greater thickness doesn't work -- the road width is independent of classification, and in parking-dense places, not easy to tell residential vs arterial at a glance. That's what the orange and white colors in the screenshot above show. (I don't think the colors there are good at all; it's just an existing color scheme that was already trying to draw curbs. So I'm iterating on the curbs there, before checking in this PR.) That experimental color scheme with the curbs is live here: http://abstreet.s3-website.us-east-2.amazonaws.com/dev/abstreet.html?--dev&--color_scheme=faded%20zoom&system/us/seattle/maps/montlake.bin&--cam=20.01/47.64100/-122.31300

A task list for me:

- [ ] Look at night mode again
- [ ] Increase the contrast of the asphalt
- [ ] Style parking lanes more dramatically
- [ ] Shift building colors away from grey; they shouldn't look anything like roads
- [ ] Try a curb even for roads without a sidewalk, like highways, for better contrast
- [ ] Overhaul traffic signal colors, and the editor icons
- [ ] Consider moving street labels out of the road. Could be related to #173
- [ ] Rethink the minimap -- remove buildings, emphasize road classification more

And addressing some feedback:

> The zebra strip spacing seems to be messed up. Should be either thicker equally spaced lines or thin lines like here

Assuming you're talking about the crosswalks, I've come across many different styles for these. It seems to be a pretty regional thing. Probably A/B Street should support multiple styles for different areas. This is also true for cycle lane coloring; I see lots of red in the UK and Europe.

> I have the same strong preference for roads that do not allow through traffic for large motor vehicles which I think would work well as a shade of grey-green

I think this more neutral grey asphalt is working better with partly transparent layers on top, so definitely need to revisit access restriction styling with this change.

**Comment by westnordost** [comment]
> not easy to tell residential vs arterial at a glance

By maxspeed? The higher the maxspeed, the broader the lanes are usually required to be.

--- 

Is there a list of traffic signs that you are displaying or are planning to display? 

---- 

>> The zebra strip spacing seems to be messed up. Should be either thicker equally spaced lines or thin lines like here

> Assuming you're talking about the crosswalks, I've come across many different styles for these. 

Really? But are they anywhere `║║    ║║    ║║` (exaggerated) instead of `║║║║║║`?

**Comment by dabreegster** [comment]
> By maxspeed? The higher the maxspeed, the broader the lanes are usually required to be.

I meant it's hard to tell visually. Which road here has more traffic?
Screenshot from 2021-07-25 14-28-10
From my memory of this place, the arterial isn't that much wider. Satellite mostly confirms:
Screenshot from 2021-07-25 14-29-08
So I'd like to somehow style arterial and local roads differently when zoomed in. This is an old experiment, maybe different shades of the grey asphalt in this PR could work.
Screenshot from 2021-07-25 14-29-52

Also in Seattle, official signed speed limit is actually kind of useless to emphasize. Most places within the city are now technically 20-25mph, whether a tiny residential road or multi-lane arterial. Of course in practice, vehicles go much faster on the arterials, because the roads are physically designed for it.

> Is there a list of traffic signs that you are displaying or are planning to display?

The only "sign" displayed is a stop sign. But more generally, the types of things we're trying to visually represent when zoomed in:
- lane configuration (including turn lanes and restrictions, buffers near bike lanes, shared bike/foot paths, etc)
- stop signs
- traffic signals (in simulation mode, we animate to communicate protected/permitted turns at any time, as well as time remaining until the signal changes)
- access restrictions (#660) -- both gated neighborhoods and different variations of low-traffic neighborhoods / streets
- Part of traffic calmed streets will soon be rendering planters, chicanes, other modal filters (#488)
And many optional layers add even more information to the zoomed-in view, like elevation/incline and heatmaps for delays, dangerous conflict points, throughput, etc

> Really? But are they anywhere ║║ ║║ ║║ (exaggerated) instead of ║║║║║║?

I don't think so... the difference there is uneven spacing between the stripes. Are we that bad?
Screenshot from 2021-07-25 14-39-35

**Comment by westnordost** [comment]
> Photos

Ah. Why are there parking lanes on the arterials though but the aerials don't show any parking cars while there are lots of parking cars on the residential road? Are you sure that parking is allowed on the arterials? If cars parked on both sides, it would only be possible to move down that road very slowly.
Also, the residential road doesn't have marked lanes. 
Not sure, but is there no distinction in OSM between "parking is not forbidden here" and "there is a dedicated parking lane here"?

As for visualizations, ideas:
- make arterials darker, residentials less dark. Would even match with how it looks like locally in Seattle as it looks like residential roads are often paved with concrete while arterials are paved with asphalt. 
- idea for traffic signals: Only draw the crossings for when there is a walk signal, otherwise make them invisible or something. Maybe works better if the crossing markings are drawn like in that image I showed because then they look like markings that block cars (continuous straight line that is orthogonal to other lane markings).
- Access restrictions: Similar idea as above. Draw a thick white/yellow line that is orthogonal to other lane markings at the entrance to private roads and gated communities. I.e., like a "wall" on the road.

**Comment by muzlee1113** [comment]
> For the minimap, you probably want a good overview for orientation, with a focus on the street layout and arterial roads
> For the main view, the focus is on street layout, so that should stand out while the rest is secondary

Totally agree with the statements and I think we can use these two principles to review the new map.

### The mini map
I think the mini map shows the different roads and the agents clearly. One concern I have is the contrast between main street (arterial) and the building:
image
It is more obvious in the downtown area since the buildings are gray and the yellow streets blend into the background and as a result less clear than the neighborhood street (in white color)
I compared it with some other maps:
image
image
1. I agree that the buildings can be removed to emphasize road on mini map. And I assume that the gray areas on the current minimap will be turned into a lighter color like #f2f0ee
2. Adding a gray border for the road like white color could draw a clearer line between the main roads and background

### The main view
The street layout is clear now with the outline of the curb and the white color palette. I agree with @westnordost and @michaelkirk that the traffic signal lines now are unclear. However, I do like the color-changing and fading animation. My suggestions are
1. I agree that we should add a similar black or dark gray border on the protected movements and adjust the z-index to make them on the top. 
2. We can adjust the "fading animation":
image
image
Now the yielded movements turn darker while the protected fade out, and then both of them turn yellow. As a result, the protected movements are less obvious and the yellow light stage becomes really more prominent than the faded green stage. Instead, I would test: a) making the transition changing from green to yellow. 2) applying on both protected and yielded movement the same fading transition but make the minimum opacity higher while making the yellow lower opacity. I do think the first solution is more natural but we can test it to see how it works.

**Comment by dabreegster** [comment]
Here are two changes applied:
1) No more buildings on the minimap. I think this isn't a controversial change at all, I'm ready to roll it out even in the current/old color scheme.
2) Using 3 shades of grey to distinguish highway (30% grey), arterial (40%), residential (50% = the previous `#7F7F7F`.
Screenshot from 2021-07-26 11-45-56
Screenshot from 2021-07-26 11-45-20

I tried blue to call out parking, but it seems a bit too loud / happy. I'll keep experimenting with tinting the grey a little bit blue or adding more markings to set it apart better.
Screenshot from 2021-07-26 11-44-50

I'll work next on traffic signals, the unzoomed view, and changing building colors. But how do the 3 greys look? I think it's much easier to find major/minor roads zoomed in now.

Catching up on comments:

> Why are there parking lanes on the arterials though but the aerials don't show any parking cars while there are lots of parking cars on the residential road?

Happens to be that one satellite photo. I promise, there's loads of parking on arterials in Seattle; this entire project kind of started because of that.

> If cars parked on both sides, it would only be possible to move down that road very slowly.

Correct. abst is starting to handle actual road widths better, so this'll eventually start to reflect in the simulation too.

> the residential road doesn't have marked lanes

I've seen massive OSM threads discussing this. I know the distinction is important. For schematic / UI purposes, A/B Street is going to act as if there's two skinny lanes on those narrow local roads. That communicates the logical use of the street better than omitting markings, I think.

> but is there no distinction in OSM between "parking is not forbidden here" and "there is a dedicated parking lane here"?

https://wiki.openstreetmap.org/wiki/Key:parking:lane
I've seen `no_stopping` used to indicate the physical lack of any shoulder space.

> What about "give way" / "priority road"?

I've seen these more in Europe. The US has some "yield" signs that I think are semantically similar. We might add them at some point. abst currently infers stop sign placement from heuristics, not any OSM data. I'd consider these signs low priority to improve.

> idea for traffic signals: Only draw the crossings for when there is a walk signal, otherwise make them invisible or something.

We used to do that long ago, but we switched to the hand/walk pedestrian signals at some point. I... don't remember why. :(   Worth revisiting.

**Comment by dabreegster** [comment]
Here are the current changes to play with: http://abstreet.s3-website.us-east-2.amazonaws.com/dev/abstreet.html?--dev&--color_scheme=faded%20zoom&system/us/phoenix/maps/tempe.bin&--cam=19.58/33.41942/-111.91219

I'm playing around with building colors right now to shift them away from grey roads. Buildings are definitely not as important to focus on. But at the very least, we want to distinguish pure residential from mixed-use / commercial. A common zoning / land-use color is reddish for commercial. So I'm trying variations of #FFD6D1 and #F2DAD9.

**Comment by dabreegster** [comment]
Here's some experiments with building colors.
Screenshot from 2021-07-26 12-34-59
Screenshot from 2021-07-26 12-34-41
Screenshot from 2021-07-26 12-34-25
Screenshot from 2021-07-26 12-34-19
The reddish commercial buildings bleed into the arterial roads in the unzoomed view. And maybe in the zoomed-in view, we could try drawing icons to represent the type of business to emphase it more -- something like
Screenshot from 2021-07-26 12-37-46
but of course not so horrible in layout. :)

**Comment by michaelkirk** [comment]
I'm really enjoying watching things move away from gray on gray on gray!

**Comment by Robinlovelace** [comment]
Overall the latest changes are looking great to me. I had a play with the example and think they greys look good:

image

Source: http://abstreet.s3-website.us-east-2.amazonaws.com/dev/abstreet.html?--dev&--color_scheme=faded%20zoom&system/us/phoenix/maps/tempe.bin&--cam=20.47/33.41826/-111.91732

In answer to your question

> how do the 3 greys look?

Good but I think there are only 2 of the 3 shown. Big improvement on the darker high contrast roads that were there previously I think. 

Regarding the loud blue colours for parking lanes, I like it, good that it stands out, you could always tone it down by selecting a slightly greyer blue. Same applies to roads that could be coloured green to show they prevent through traffic for large vehicles, being somewhere between a cycle lane and a normal road.

**Comment by Robinlovelace** [comment]
Random comment on the new boundary colour when selecting a new city: pretty garish.

image

**Comment by Robinlovelace** [comment]
Looking at a part of Leeds I know at relatively low zoom level, I really, really like it.

image

Source: http://abstreet.s3-website.us-east-2.amazonaws.com/dev/abstreet.html?--dev&--color_scheme=faded%20zoom&system/gb/leeds/maps/north.bin&--cam=15.26/53.82132/-1.53665

**Comment by Robinlovelace** [comment]
I've found a place with the three types of grey, darker being bigger roads it seems, which makes sense. I think this looks good.

image

Source: http://abstreet.s3-website.us-east-2.amazonaws.com/dev/abstreet.html?--dev&--color_scheme=faded%20zoom&system/gb/leeds/maps/north.bin&--cam=20.75/53.80841/-1.53427

**Comment by westnordost** [comment]
> how do the 3 greys look? I think it's much easier to find major/minor roads zoomed in now.

I like it! 

> I tried blue to call out parking, but it seems a bit too loud / happy.

Maybe too light? It could also have less saturation after all. In the screenshot above, the parking lane doesn't have the same lightness as the bus or the cycle lane. You could also play around with 🅿️ sprites, but I think this would make the parking lane look too busy, i.e. too much standing out.

I saw the private road coloring. Some more mockups:
image

**Comment by muzlee1113** [comment]
> how do the 3 greys look? I think it's much easier to find major/minor roads zoomed in now.

I like it! 

> I tried blue to call out parking, but it seems a bit too loud / happy. I'll keep experimenting with tinting the grey a little bit blue or adding more markings to set it apart better.

I think applying a different pattern might be a better than different color. Can I learn more about the context of the request for calling out parking? Also, compared with the parking availability overlay, the use cases for calling it out on the main map?

> The reddish commercial buildings bleed into the arterial roads in the unzoomed view. And maybe in the zoomed-in view, we could try drawing icons to represent the type of business to emphase it more -- something like

Based on the screenshot I do feel like the buildings are too loud. I like the idea to make the game more colorful, but I have some concerns about distracting attention from the roads/traffic. Have you considered make building type a layer/overlay, rather than on the main map. If we do want to push it to the main map, I feel like we might want a legend for them, including the different road types too. Also, to avoid blending with roads, try applying a gray-scale outline like white or light gray.

**Comment by dabreegster** [comment]
Next round! It'll be a few minutes, but the web demo will be updated. abstreet.s3-website.us-east-2.amazonaws.com/dev/abstreet.html?--dev&system/us/seattle/maps/udistrict.bin is a good map showing off all the patterns.

Screenshot from 2021-07-26 18-09-17
Screenshot from 2021-07-26 18-09-09
Screenshot from 2021-07-26 18-09-03
Screenshot from 2021-07-26 18-08-49

1) I'm trying `#C5D2E5` for residential buildings and a darker `#99aecc` for commercial.
2) I thickened building outlines for both zoomed/unzoomed, and added a black outline for unzoomed roads. (It currently looks a bit buggy; it doesn't cover intersections. If we like this idea, I'll fix it up.)
3) Finally trying Robin's green asphalt for traffic-calmed/privateish roads. I took the bike lane color and made it less bold, `#6fb193`.

Which of these ideas seems like it works, or should I try some variations? For color picking, I've just been using various tools to adjust the shade/tint; even though a few people have tried to teach me more theory behind picking good colors, I haven't internalized the lessons well enough yet. :(

> Random comment on the new boundary colour when selecting a new city: pretty garish.

Agreed. There's probably lots of secondary colors we'll have to adjust. Also agent colors, zoomed and unzoomed. This whole design exercise is kind of intense, since everything is changing. I'm trying to pin down the zoomed view, then the unzoomed, then all of the UI stuff around it. Then.. maybe night mode. ^^;

> I saw the private road coloring. Some more mockups:

Thanks for these! I think for gated communities, the "private" sign probably works the most clearly for the zoomed in view. For LTNs/greenways, I'll try bollards/planters. First step for me is calculating the actual boundary within the intersection where some turns are restricted.

> Can I learn more about the context of the request for calling out parking?

I'm also curious. I don't think we should call out parking lanes so dramatically in the main zoomed view. Indeed the parking layer can be used to point these out.

> Based on the screenshot I do feel like the buildings are too loud

How do the new colors look? Still too distracting? Is there a general way to start with something that looks decent visually like `#C5D2E5` and `#99aecc` and "de-emphasize" it? Like lowering saturation, hue, brightness?

> Have you considered make building type a layer/overlay, rather than on the main map

We have some form of this; the "amenity" layer. I agree we shouldn't overwhelm with too much detail by default. The only distinction I feel is important is between pure residential buildings and those with some kind of public/commercial space.

> Also, to avoid blending with roads, try applying a gray-scale outline like white or light gray.

I adjusted the outline, see screenshots or web demo above

**Comment by michaelkirk** [comment]
Unintentionally or not, you've arrived at this evocative "sketch" style, which I'm really digging:

**Comment by muzlee1113** [comment]
I think the black outlines are probably too strong. I would suggest a more subtle outline like #F2F2F2 and #D6D6D6. If you want me to help to adjust it, we can find a time and take a look together too.

**Comment by dabreegster** [comment]
I made some improvements to the road outlines, fixing z-ordering and tracing along the edge of intersections. Now the only place where lines overlap and look buggy are places where our map geometry is still legitimately broken -- even more motivation to fix those faster! Shown with the bold black color to debug easily.

Screenshot from 2021-07-28 12-16-54
Screenshot from 2021-07-28 12-15-21


> Unintentionally or not, you've arrived at this evocative "sketch" style, which I'm really digging

Yeah, I'm not sure what this reminds me of, but it's very "diagram" like!

> I think the black outlines are probably too strong. I would suggest a more subtle outline like #F2F2F2 and #D6D6D6. 

Here are those two. `#F2F2F2` is too close to the local street white color, but `#D6D6D6` makes that subtle drop shadow effect.

Screenshot from 2021-07-28 12-14-54
Screenshot from 2021-07-28 12-14-26

**Comment by dabreegster** [comment]
> making the transition changing from green to yellow

screencast

A linear interpolation from green to yellow looks super strange to me; it's a "sickly" color. :P  For the moment, I'll stick to the solid green suddenly changing to yellow when there's 5 seconds left, since this is closer to reality. But I did add the outlines and adjust z-ordering.

**Comment by dabreegster** [comment]
Screenshot from 2021-08-01 12-26-26
An experiment making the 3 road class colors even more distinct. But local roads wind up too faded, and this is a bit too much.

**Comment by dabreegster** [comment]
I fixed all the blocking problems and cut over to this new scheme as the default! It'll be in the new release in a few hours.

Thank you all for the help! The result looks awesome.

Still lots of further design work to support this change even better. Tracked in #74

**Pull request merged**
