### PR TITLE
Rip out the code that tries to build the bus route data from OSM.

### PR DESCRIPTION
**Pull request by dabreegster**
@tnederlof, here's the quick example cleaning up the existing attempt to import bus routes from OSM. Mostly it just rips out code.

I think the long-term nice thing would be to put the URL to a GTFS .zip file in the `GenericCityImporter` config, fill it out in `importer/config/us/nyc/cfg.json` for example, do the downloading and unzipping automatically.

Then in the `convert_osm` crate, read the raw GTFS data and fill out stuff in `RawMap` that's needed later. Dunno if the current `RawBusRoute` structs have the right fields.

Then the last step is in `map_model/src/make/transit.rs`. This transforms the `RawMap` stuff and builds the final `BusRoute` and `BusStop` objects in the map model.

### CODE REVIEW

**Comment by dabreegster** [comment]
Depending how you want to prototype, I can clean this up and wire up the downloading and stuff, so you can just focus on using the data. Up to you

**Comment by tnederlof** [comment]
Thank you for doing this, I am starting to envision how the pieces fit together. This seems like a good starting point, I will take a shot at things and just ping you as needed.

**Comment by matkoniecz** [comment]
So the plan is to use GTFS or nothing, without fallback to OSM based routes?

**Comment by dabreegster** [comment]
> So the plan is to use GTFS or nothing, without fallback to OSM based routes?

I wouldn't say there's a set plan yet; Trevor is experimenting with just using GTFS right now. Trying to use the OSM routes was hard at the level of detail I originally attempted, but maybe settling for something simpler could work. OSM has more detail about the relationship between bus/train stops and platforms when they're more complex than the bus stopping next to the sidewalk with a sign. But attempting to figure out the path the bus takes from OSM was a mess -- stitching together the ways in the correct order and handling when weird parts of roundabouts weren't mapped.

**Comment by dabreegster** [comment]
Closing in favor of #808

**Pull request closed without merging**
