### PR TITLE
Rearrange intersection geometry code and start goldenfile tests to pi…

### PR DESCRIPTION
**Pull request by dabreegster**
…ck up changes. #846

In https://github.com/a-b-street/osm2lanes/issues/117, we're discussing the larger picture of transforming raw OSM into nicely rendered streets, both for use in A/B Street and new OSM tooling (like JOSM and iD plugins). This PR is a small start to one piece of that. The [intersection geometry algorithm](https://a-b-street.github.io/docs/tech/map/geometry/index.html) in A/B Street is now structured in a way where input for a single intersection can be saved as GeoJSON, fed into the algorithm, and the output written as GeoJSON. This gives us a meaningful way to unit test this piece in isolation. (Previously, [screenshot diffs](https://a-b-street.github.io/docs/tech/dev/testing.html#screenshot-diffs) of entire maps were used, but it's quite hard to quickly iterate on these.) Restructuring this is also a step towards splitting out a totally independent crate for this process, though I'm having some doubts that's what we'll want to do.

@BudgieInWA, at your leisure let me know what direction you think we ought to go -- put effort into splitting out this crate that maybe doesn't tackle a large-enough scope, or take more focused steps towards `osm2streets`. Also feel free to review the code, but disclaimer that I wasn't going for cleanliness or anything. @droogmic may also be interested in this.

## Scope

The `osm2polygon` method (maybe not the right name, but starting with it for now) takes in info about all of the road segments connected to one intersection. It then calculates the geometry for that intersection and trims back the road center-lines. This happens in a total vacuum -- small roads nearby aren't part of the input. A/B Street currently does some tricks to handle complex junctions, where we run this algorithm near tiny roads, then later remove the tiny roads and use all the small polygons to form one big intersection polygon. That isn't wired up through the `osm2polygon` API or part of the tests.

## Splitting out a crate

We could go two directions from here. The one I'm leaning towards is to not split or move this code anywhere, but simply to start taking advantage of goldenfile tests to more quickly iterate on core intersection geometry work.

The other direction, which I was pursuing at first, was to split out this `osm2polygon` as an independent crate in its own repo, just like `osm2lanes`. This would be a step towards contributors working on that independently of the rest of the A/B Street codebase, and in directly using the library in other tools -- like say a JS slippy map that draws road/intersection geometry as you pan around.

However, the discussion in https://github.com/a-b-street/osm2lanes/issues/117 makes me rethink that, because the API here of looking at one intersection in isolation doesn't really seem like it'll help us solve any of the interesting/hard problems with geometry. If anything, the [raw_map](https://github.com/a-b-street/abstreet/tree/master/raw_map/src) crate (already partly factored out) might be the better place to start for `osm2streets`. It has the graph, plugs into `osm2lanes`, contains this intersection geometry logic, and is [the place](https://github.com/a-b-street/abstreet/tree/master/raw_map/src/transform) where I've been experimenting with modifying the graph based on geometry (like collapsing short dog-leg intersections or trying to snap together dual carriageways).

A second complication with bringing the current `osm2polygon` into its very own repo is dependencies. It uses some parts of A/B Street code that would ideally themselves be split out into a common library -- namely [geom](https://github.com/a-b-street/abstreet/tree/master/geom/src). But as #846 discusses, lots of this geometry code is buggy and not cleanly designed itself. It'd be far more ideal to only depend on georust crates, and maybe contribute missing things -- particularly shifting a linestring perpendicularly -- to existing crates.

## How to work with the current tests

There's an internal "map editor" tool that works on `RawMap`. I added an option to export a single intersection from there. There are some instructions for running this tool locally, or you can try it quickly at play.abstreet.org/0.3.18/map_editor.html?../../dev/data/input/us/seattle/raw_maps/montlake.bin -- but it won't write the output files properly (they'll wind up in browser local storage!).

I've been using https://pypi.org/project/geojsonio/ as a quick tool to view the geojson input and output files. QGIS also works, but it's slower to startup. It'd be great to eventually have some workflow for visually diffing two files when the output changes.

### CODE REVIEW

**Comment by dabreegster** [comment]
Oh yeah, and github has nice geojson viewers too if you "view file" near the diff: https://github.com/a-b-street/abstreet/blob/2a7d16170e924cfedac58da00c57489db825986b/raw_map/src/geometry/tests/53101721_output.json

**Comment by BudgieInWA** [comment]
I agree that going directly from OSM ways to road & intersection polygons is too much of a jump; it skips over too many important questions, like "which ways make up this intersection". Those questions are where all of the messyness is, I think: with a normalised representation of roads and intersections, drawing the road becomes a much more straightforward problem (at least as "straight forward" as you can describe computational geometry).

I think the most valuable independent tool, would be one that takes OSM ways and produces a normalised representation, that is designed for the ease of use for the consumer, leaving behind the compromises and alternative requirements of the OSM schema.

It sounds like `RawMap` is the part of A/B Street that achieves this, and is therefore the place that I think we ought to be looking. I'm not sure quite what that implies, but I feel like test cases like "these 3 ways represents a single road becoming a duel carriageway" and "these *N* nodes represents a single intersection" is the goal.

I feel like I need to sit down an talk about this to stop myself going around in circles in my head...

**Comment by dabreegster** [comment]
> I feel like I need to sit down an talk about this to stop myself going around in circles in my head...

If it makes sense to chat over this in a call, let me know.

> It sounds like RawMap is the part of A/B Street that achieves this, and is therefore the place that I think we ought to be looking. I'm not sure quite what that implies

Aside from the test cases you mention, I think it gives us an idea what to refactor a bit more strongly. `RawMap` currently has a bunch of stuff scraped from OSM and other sources (GTFS, parking); maybe we first hone in on just the pieces needed for the osm2streets pipeline, and ignore [buildings, parking lots, etc](https://github.com/a-b-street/abstreet/blob/27e94662e8759ac8fd47a6c566e971f1de6b72af/raw_map/src/lib.rs#L52).

Second, it may be time to re-think how we transform OSM into this intermediate raw map representation. [convert_osm](https://github.com/a-b-street/abstreet/tree/master/convert_osm/src) does this currently, but it's a misnomer of a crate, as it's also got stuff to grab elevation data, GTFS, etc. Depending how else we want to feed in OSM data -- maybe streaming from overpass or reading PBF instead of XML -- some changes here could happen.

And then there is the question of the `map_editor` tool -- it's even more tightly coupled to weird A/B Street quirks, like the UI library. If the effort that's been invested there already is useful to preserve, we have to decide how that fits in with the goal of cleanly splitting out some more reusable libraries.

But maybe these cleanups aren't that important in the short term.

> test cases like "these 3 ways represents a single road becoming a duel carriageway" and "these N nodes represents a single intersection" is the goal.

Yeah, this sounds like the more interesting thing to figure out in the short term. Some example implementations that exist, to give a flavor of how modifying the graph works right now:

- [detect dual carriageways](https://github.com/a-b-street/abstreet/blob/master/raw_map/src/transform/dual_carriageways.rs) (actually just tiny roads in between dual carriageways)
- [removing a short road from the graph](https://github.com/a-b-street/abstreet/blob/master/raw_map/src/transform/merge_short_road.rs) while trying to preserve turn restrictions in their various forms
- [look for dog-leg intersections to collapse](https://github.com/a-b-street/abstreet/blob/27e94662e8759ac8fd47a6c566e971f1de6b72af/raw_map/src/transform/find_short_roads.rs#L118)

And none of these interesting transformations has tests at this level. Maybe we should sketch out what that'd look like. Is the input a clipped osm.xml, probably, and the expected output a piece of these RawMaps? (Since the format of RawMaps changes, that's a complication)

**Comment by dabreegster** [comment]
Maybe a more interesting example trying to work with `RawMap`, collapsing the "sausage link" effect from dual carriageways.
https://github.com/a-b-street/abstreet/tree/sausage_links
I need to revive this and remember what was proving to be hard. For the geometry, looks like I was just taking the polyline of one of the ways and not trying to "average" the two pieces of a loop. The harder part was actually gluing the two lists of lanes together! It'd be very good to revisit that now and make sure the osm2lanes approach will help there.

**Comment by droogmic** [comment]
Hi Dustin,

It's hard for me to jump in cold and comment on this discussion.
In general the changes look good, and I have no strong opinions on most of the design directions you have raised.

Instead: I turn the question around, how/where would you like help developing onward from this, because I assume there is a lot of progress to be made in a similar direction?

**Comment by dabreegster** [comment]
> how/where would you like help developing onward from this, because I assume there is a lot of progress to be made in a similar direction?

I'd love help in a few areas:

1) Transformations that detect and simplify situations that OSM models in an awkward way. One example is dual carriageways where the overall road width is essentially the same, but turn lanes / the median trade off width regularly, such as https://www.openstreetmap.org/node/670081548. A possibly more limited case is dual carriageways that form "sausage links" as they merge/split, like https://www.openstreetmap.org/way/968531504 and https://www.openstreetmap.org/node/4347547495. I think the `RawMap` could be the right level of abstraction of graph + lanes + geometry + turn restrictions to operate on, but very likely we'll need to change it.

2) Setting up a way to iterate more quickly on these types of transformations -- probably through tests. We have to first discuss what the input and output look like there...

3) Implementing support for `placement` and other center line transformations; there's nothing at all today, and motorway entrances/exits look particularly bad as a result.

The main open question in my mind is how to split out `RawMap` into a separate repository so we can iterate quickly like with `osm2lanes` and set ourselves up for easily hooking into other end-user apps later. The RawMap stuff has more dependencies on the geometry crate in A/B Street -- maybe that gets split out into the same repo, and we slowly improve it or trim it down and rely on other, more robust crates. Another question is what to do with the UI for manipulating RawMaps -- it's quite handy for debugging and I don't want to throw away all the effort, but it uses a very weird UI library that'll be unfamiliar to learn and is far from ideal.
Screenshot from 2022-04-12 09-04-55

I'm likely in the best position to do sweeping refactors and split the codebase, but I'm quite uncertain what to split yet. Maybe I get y'all's help setting up tests or working on some of these transformations in this repo, then once we all have a more clear picture how things work now and where we'd like to go, we make a split?

**Comment by droogmic** [comment]
From what I understand, I agree that the biggest hurdle to clear is good testing.
Testing what I have seen so far seems something like UI testing, you either do it manually, or any small graphical difference could start breaking overly stiff tests.

I guess the only way to do this is to use extremely simplified manufactured test input and output data?

Something like:
```
in:
    ways:
    - [(-8,0), (0,0)]
    - [(0, 0), (8,0)]
    - [(0,8), [0,0)]
    - [(0,0), [0,-8)]
out:
    area:
    - (8,1)
    - (1,1)
    - (1, 8)
    - (-1, 8)
    - (-1, 1)
    - (-8, 1)
    - (-8, -1)
    - (-1, -1)
    - (-1, -8)
    - (1. -8)
    - (1, -1)
    - (8, -1)
```

But even that might be problematic?

**Comment by dabreegster** [comment]
> Testing what I have seen so far seems something like UI testing, you either do it manually, or any small graphical difference could start breaking overly stiff tests.

Correct, A/B Street's [screenshot diffs](https://a-b-street.github.io/docs/tech/dev/testing.html#screenshot-diffs) are pretty brittle and too "coarse" -- they cover an entire imported area.

> I guess the only way to do this is to use extremely simplified manufactured test input and output data?

For both the test input and output, I think it's important for a human to be able to easily produce it and to understand diffs in it. I don't think the simplified coordinates example does either. This PR makes a little progress -- it expresses the [input](https://github.com/a-b-street/abstreet/blob/2a7d16170e924cfedac58da00c57489db825986b/raw_map/src/geometry/tests/244420071_input.json) and [expected output](https://github.com/a-b-street/abstreet/blob/2a7d16170e924cfedac58da00c57489db825986b/raw_map/src/geometry/tests/244420071_output.json) as GeoJSON. I added a tool to dump the input from an existing UI. If we work on the code and see a diff in the output, looking at the geojson text directly isn't really helpful, but we can load the before/after in QGIS or geojson.io or so and visually compare.

I think this PR just focuses on too narrow a problem. The intersection polygon algorithm takes the thick road center-lines and trims them back and makes a polygon for the intersection. There are probably some edge cases to fix, but it's looking like most of the interesting work is elsewhere. How are the road center-lines produced in the first place? `placement` tags mean the coordinates in OSM need to be transformed. What road center-lines should even go into the algorithm in the first place? Well, we probably want to collapse dual carriageways into one line.

So I think the direction for tests that feels most plausible is XML .osm as input, sliced to somewhat small areas around an interesting junction or along a dual carriageway that joins/splits repeatedly. The output could maybe be expressed in two distinct stages, and maybe we test each of those separately. The first is what we're calling `RawMap` right now -- just the transformed and consolidated road center lines and intersections as points. The second is the geometry of those thickened roads and intersections. Both could probably just be GeoJSON, since it's visual and lets us stick whatever properties we want.

**Comment by BudgieInWA** [comment]
> The output could maybe be expressed in two distinct stages, and maybe we test each of those separately. The first is what we're calling RawMap right now -- just the transformed and consolidated road center lines and intersections as points. The second is the geometry of those thickened roads and intersections.

I think this is the ticket. `placement` tags are just the first way that OSM geometry needs transforming, so get that all out of the way first. This is the place where all those transforms happen, too. 

> Maybe I get y'all's help setting up tests or working on some of these transformations in this repo, then once we all have a more clear picture how things work now and where we'd like to go, we make a split?.

This sounds sensible too. I would like to look at transformations (and learn how RawMap works in the process). I understand a bit about motorway exits and sausage links (which are the same problem), which I think has implications on the RawMap representation -- I'll see how it looks.

### Testing

I like the sound of working towards testability, partly because an interface that is good for testing feels like it would be a good interface for exporting / to standardise on.

The mentioned GEOJSON test feel like the right direction to me; they simplify by zooming in on one intersection / interesting feature, but fit into the rest of the ecosystem, for powerful debugging. 

Maybe a project is a tool that looks at some cirle, turns the osm into output for viewing in a powerful way, which can easily be turned into a goldenfile test. Could we use the RawMap editor to create target results by hand, to have as part of the comparison? 

The osm geom library is probably its own library or project eventually -- a solid foundation with at least everything that the the OSM schemas expect: parallel ways/linestrings / fat line strings; areas, intersections/unions, ...  There seems to actually be a lot of trickyness that could go into interpreting curves out of the samples that OSM provides.

### What Next?

It seems like there are a lot of different ideas here that could each be projects, that should probably spawn their own discussions. Does a `ROADMAP.md` need to exist to hold these ideas, so they aren't lost to the archives of some closed PR?

@dabreegster, I would love to be introduced to rawmap on screenshare, to come up with a plan for working on some transformation.

**Comment by dabreegster** [comment]
> Maybe a project is a tool that looks at some cirle, turns the osm into output for viewing in a powerful way, which can easily be turned into a goldenfile test.

The pipeline could look like this maybe:

1) Use Overpass to get a boundary from OSM
2) Transform into a RawMap (convert_osm crate, currently)
3) Apply transformations to the RawMap -- such as adjusting a road's center line based on placement, merging short roads, etc. Output is still a RawMap
4) Dump to GeoJSON with low fidelity -- a polygon with attributes per road and intersection, like the examples below
5) Or dump to GeoJSON with high fidelity -- I guess this is the `streets2geom` piece. Based on lane separators from osm2lanes, render those too. Trace where the pavement around an intersection meets each other. Eventually, show different types of crossings.

> Could we use the RawMap editor to create target results by hand, to have as part of the comparison?

It only supports a few types of changes today, like dragging points around. We could definitely add more, like shifting a road center-line left/right.


https://user-images.githubusercontent.com/1664407/163360990-fe57e58a-f413-4d6a-865b-61a52965cf2f.mp4

>  There seems to actually be a lot of trickyness that could go into interpreting curves out of the samples that OSM provides.

Yup. I think this should be properly built on top of https://georust.org/, which has support for some of this. I started `geom` early on before some of this existed, or because I wanted stronger invariants about line strings. But I just hacked stuff together, like [line string shifting](https://github.com/a-b-street/abstreet/blob/9ffab3c976f173fe6b8686d29c8bcc895a2c0ee5/geom/src/polyline.rs#L459). We may have to wind up porting better algorithms (and contribute to georust in the process!)

> Does a ROADMAP.md need to exist to hold these ideas, so they aren't lost to the archives of some closed PR?

Sure, seems a bit safer than an issue with lots of discussion piling on.

> I would love to be introduced to rawmap on screenshare, to come up with a plan for working on some transformation.

I'll email you...

**Comment by dabreegster** [comment]
I'm going to merge this, because it carves out an approach to goldenfile testing with GeoJSON, even if it's probably happening at the wrong stage. My next steps are to get easy instructions for a dev environment with the RawMap editor, and to revisit RawMap vs InitialMap to make iterating on the code more easily. Main requirement is being able to modify a road's points independentlyish of the graph structure. First big change we can think about making is a transformation that applies placement tags.

**Comment by dabreegster** [comment]
I'm going to merge this, because it carves out an approach to goldenfile testing with GeoJSON, even if it's probably happening at the wrong stage. My next steps are to get easy instructions for a dev environment with the RawMap editor, and to revisit RawMap vs InitialMap to make iterating on the code more easily. Main requirement is being able to modify a road's points independentlyish of the graph structure. First big change we can think about making is a transformation that applies placement tags.

**Pull request merged**
