### PR TITLE
No right on red

### PR DESCRIPTION
**Pull request by mdejean**
In most places outside North America, as well as in NYC, Montreal, and Mexico City, right turns are not permitted on red except where specifically indicated. This PR adds a map config option for turn on red which is true by default and false for nyc (need to add the others).

It then ignores yield turns which don't share a stage with a (green) protected stage in `make_stages`. This doesn't affect the traffic signal generators which don't use `make_stages`. Perhaps it would be better to do even less, and just alter the literals in `four_way_two_stage` etc?

### CODE REVIEW

**Comment by dabreegster** [comment]
Nice! The results look correct in NY.

> Perhaps it would be better to do even less, and just alter the literals in four_way_two_stage etc?

I like the simplicity of the implementation right now. We could add conditions to

```
        vec![   
            vec![
                (vec![north, south], TurnType::Straight, PROTECTED),
                (vec![north, south], TurnType::Right, YIELD),
                (vec![north, south], TurnType::Left, YIELD),
                (vec![east, west], TurnType::Right, YIELD),
            ],
            vec![
                (vec![east, west], TurnType::Straight, PROTECTED),
                (vec![east, west], TurnType::Right, YIELD),
                (vec![east, west], TurnType::Left, YIELD),
                (vec![north, south], TurnType::Right, YIELD),
            ],
        ],
```

but I think it would hurt readability a bit. `make_stages` already makes other transformations like swapping left/right in the UK. So I'm in favor of the way you've written it.

> This doesn't affect the traffic signal generators which don't use `make_stages`

We could alternatively filter out the yield turns at the end of `get_possible_policies`, near `// Make sure all possible policies have a minimum crosswalk time enforced`. That would also handle `greedy_assignment` and others. I don't think this is too important, since if all the generators using `make_stages` fail and the first working policy is one of these other ones, the results aren't realistic anyway.

> This PR adds a map config option for turn on red which is true by default and false for nyc (need to add the others).

Right, in terms of merging this PR, we need to

1) Update all of the config files... which is getting quite annoying to do frequently. Maybe it's time to rethink this config. Most places use defaults, but they have to be manually copied around.

2) Regenerate all the maps, since adding to `MapConfig` is binary incompatible

**Comment by dabreegster** [comment]
I updated the config files. I'll try and regenerate all the maps tonight, then merge this in.

I'm also looking into ideas for cleaning up all the map config and the maintenance burden of adding fields...

**Comment by mdejean** [comment]
I changed the non-US maps to "turn_on_red": false

**Comment by dabreegster** [comment]
Awesome! Regenerating all the maps now, then I think we can merge?

**Comment by dabreegster** [comment]
Thanks for the PR! This is a nice step towards more accurate modelling especially outside the US. I've regenerated all the maps, since the binary format changed. Merging!

**Pull request merged**
