### PR TITLE
When calculating LTN cells, don't cross bike-only roads.

### PR DESCRIPTION
**Pull request by dabreegster**
Problem: there's a bike/foot-only road in the middle of the blue area, so the partitioning into cells is wrong:
Screenshot from 2021-12-16 14-04-13

This PR treats roads inaccessible to cars as already filtered. Now we get:
Screenshot from 2021-12-16 14-05-23
Which is better, but there are some issues exposed... The view by streets maybe shows it a little better:
Screenshot from 2021-12-16 14-05-50

I'm not sure how to classify non-motorized roads. The point of a cell is to show all the contiguous area a driver can reach without leaving the neighborhood. Maybe the "cells" based on already-filtered roads should just be invisible, treated as internal gaps in the neighborhood?

When we start looking at measurements based on all buildings with the neighborhood -- such as how far do they have to drive to reach the perimeter -- we'll have to do something about buildings snapped to a non-motorized road and existing in one of these invisible cells.

### CODE REVIEW

**Comment by dabreegster** [comment]
@Robinlovelace, I think you pointed out an example of this bug in Leeds:
Screenshot from 2021-12-16 14-09-41
With this draft PR, it becomes:
Screenshot from 2021-12-16 14-10-25
Which is better, but of course all the different "cells" clustered around these non-car roads is kind of wrong.

**Comment by Robinlovelace** [comment]
Looks like progress! The example in Leeds I was looking at was in Chapeltown, just West of Chapeltown Road, can take a look at before and after there if that would be of interest?

**Comment by dabreegster** [comment]
Ah, I remember the area now! No need to look yet, I'll find a better way of handling the cells containing bike-only roads and then check with you when I have a proposal for fixing.

**Comment by dabreegster** [comment]
I wound up doing this somewhat cautiously -- first I used the 4-color theorem to make sure adjacent cells are colored differently, to be able to see the results of bike-only cells clearly: 332e88f235d0b59c81d1161712da97d99c7fc5d7

Every car-free road segment creates its own little cell around it as usual; otherwise, surrounding cells "bled" into it in ways that didn't make sense. I decided to style them all as green.

I tested in a bunch of places, and the results all seem correct to me. From here on, if the LTN tool fails to recognize a modal filter or restriction that exists in the real world, it's either missing data in OSM or a bug on my end, and in either case, please tell me about it!

Again, green cells are car-free. Demos:
Screenshot from 2021-12-31 16-20-25
Screenshot from 2021-12-31 16-20-51
This is super close to where I live now; the little specks of green are indeed all filtered. But notice how they don't actually split up the big yellow cell; there's other ways to route around.

If you happen to pick a cell encompassing a park that has roads in it, now it generally gets styled as car-free:
Screenshot from 2021-12-31 16-22-33
This will be much more important soon when all footways from OSM are imported!

Some Leeds examples:
Screenshot from 2021-12-31 16-23-30
Screenshot from 2021-12-31 16-23-44

I don't remember where the Chapeltown road example was, maybe it was the little vertical strip of trail between Savile Dr and Mexborough Place?
Screenshot from 2021-12-31 16-26-42

**Pull request merged**
