### PR TITLE
Add Milwaukee

### PR DESCRIPTION
**Pull request by tnederlof**
@dabreegster I was able to follow the instructions in the docs to add Milwaukee as a map. I ended up doing one for the entire city and another box for the Oak Creek area (which is one area of research for me currently). Please let me know if you need anything else from me.

### CODE REVIEW

**Comment by dabreegster** [comment]
Hi Trevor!

1) You can remove `elevation_input/query`; that's not meant to be committed. Part of the import process tries to run a Docker container that for gathering SRTM elevation data. But the container isn't on DockerHub yet, so it literally only works on my machine -- I still need to finish productionizing this part. In the meantime, we could also add `elevation_input/query` to `.gitignore` to prevent other people from hitting this issue.

2) The boundaries are huge. The smaller one, Oak Creek, comes out to 167MB for the final map (`data/system/us/milwaukee/maps/oak_creek.bin`). There's not a specific limit in place, but it's going to be hard to iterate quickly on large areas like this -- just try loading Oak Creek in the UI when running in debug mode (compiling without `--release`). I would recommend splitting into smaller pieces, which can overlap if needed. An example for Paris:
Screenshot from 2021-04-26 09-45-13

It may take a bit of trial-and-error to tune the size. It also depends what you're looking to study. In Seattle, we've carved out a bunch of small regions just to focus on particular roads:
Screenshot from 2021-04-26 09-46-38

**Comment by dabreegster** [comment]
`git rm elevation_input/query` should work. Adding a file to `.gitignore` doesn't automatically remove it from version control, it just prevents it from being added accidentally later

**Comment by tnederlof** [comment]
Sorry for all of the commits @dabreegster I am a bit rusty. Should be straightened out now. I tried to select much smaller areas, hopefully, the sizes are tolerable.

**Comment by dabreegster** [comment]
No worries, I remember how long figuring out gitignore took the first time.

The map size is much better now! Two more tweaks, and I think we're good to go.

1) Rename the map to just `downtown`. Since the maps are already scoped to a country and city, I'm trying to avoid repeating `downtown_milwaukee` in the map name
2) Let's adjust the downtown boundary to this:

```
boundary
1
     -87.89968013763428    43.023772650062504
     -87.88320064544678    43.025749189659685
     -87.87135601043701    43.05962282888517
     -87.93572902679443    43.06106517973023
     -87.9391622543335    43.02261179555704
     -87.89968013763428    43.023772650062504
END
END
```

The one in the PR right now winds up looking like this:
Screenshot from 2021-04-26 17-59-17
This is due to #32. Through trial and error, I figured out that we were clipping the southern edge of https://www.openstreetmap.org/relation/5900827, and the algorithm that tries to create water polygons got confused. If we just cover the full southern end of it, it looks much better:
Screenshot from 2021-04-26 18-09-27

**Comment by tnederlof** [comment]
Thank you for the new bbox!

**Comment by dabreegster** [comment]
Thanks for the patience with this process! Everything here looks good, so I'll squash merge and push the pre-built maps to S3.

**Pull request merged**
