### PR TITLE
Begin a radical simplification of the LTN tool's color scheme, based on

### PR DESCRIPTION
**Pull request by dabreegster**
generous advice from Duncan Geere.   #911

- Remove most color from the basemap, mimicking Mapbox light
- Stop drawing cells as colored areas. Just draw the thick boundary
  between adjacent cells, showing that they're separated.

The previous behavior with colored cell areas is still available as an
advanced option, but disabled by default.

Preview:

https://user-images.githubusercontent.com/1664407/178152315-3eff2b70-45df-41eb-9d37-5408f1da4cfb.mp4

More work needed:

- [ ] We try to erase the cell boundary next to the neighbourhood perimeter (because the cell is "connected" to the perimeter road), but it's imperfect sometimes
- [ ] The basemap still has some loud colors/styling that needs adjustment for unimportant features. Map border intersections, traffic signals, parking lots, bike trails.
- [ ] Road labels are a bit hard to see. Black is now a bit overloaded of a color.
- [x] Cell borders are a bit hard to see

### CODE REVIEW

**Comment by dabreegster** [comment]
https://user-images.githubusercontent.com/1664407/178220989-80515c14-b395-469a-99bc-dbe85dc85e95.mp4

The next (IMO) improvement: lightly highlight a cell while hovering on it, to emphasize that it's an area, and loudly highlight the arrows showing entrances/exits to the perimeter road.

**Comment by dabreegster** [comment]
@Robinlovelace thanks for the feedback! It might be hard to tell just from the videos, but any ideas for improvement or opinions about things still hard to see? Personally, the road labels are still cluttered / not in the right places

**Comment by Robinlovelace** [comment]
Couple of more-or-less random thoughts:

- Road names seem too big now: especially as only some of them have them I think they would benefit from being smaller
- Legend in the empty space to the left showing, for example that the thick black line (which may be too thick and benefit from being more subtle) could be smaller

Artists impression of possible changes incoming...

**Comment by Robinlovelace** [comment]
Image for ya @dabreegster !

image

**Comment by dabreegster** [comment]
Thanks @Robinlovelace!

1) Labels are probably still overcomplicated right now. I'll try just drawing them inside the bounds of the road, meaning they're very small / hard to read at certain zoom levels. The current system (that tries to keep the label text roughly the same size on the screen as you zoom) is appropriate for low zoom levels, but at this level, we should switch to something else.

2) A legend is a great idea. We're finally narrowing the use of color down. Red = shortcuts. Green = the modal filter icon (soon!). Yellow = the highlighted cell and arrows. Thick black = separation between cells.

**Comment by Robinlovelace** [comment]
> 1. I'll try just drawing them inside the bounds of the road, meaning they're very small / hard to read at certain zoom levels.

I think that's a good approach. You're only likely to want to know that level of detail when you zoom in and that's roughly how the most popular web mapping system (Google Maps) works.

Awesome, re legends, so frustrating when maps lack legends, especially for first time users. Any input you want from me on that just shout!

**Comment by dabreegster** [comment]
https://user-images.githubusercontent.com/1664407/178971944-a3fb3ffc-5bce-4551-97df-50b627872c02.mp4

I adjusted the styling for cyclepaths and railroads, and I think everything is good enough to push forward as the default. Many remaining design changes:

- better road labels
- a legend
- switch to a different modal filter icon

**Pull request merged**
